# Generated by Django 3.2.8 on 2021-10-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.TextField()),
            ],
            options={
                'db_table': 'bot_names',
            },
        ),
    ]
