# Generated by Django 3.2.8 on 2021-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='botnames',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
