# Generated by Django 3.2.8 on 2021-11-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_botnames_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botdetails',
            old_name='media',
            new_name='qmedia',
        ),
        migrations.AddField(
            model_name='botdetails',
            name='amedia',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
