# Generated by Django 3.2.8 on 2021-11-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211106_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='botdetails',
            name='first_question',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
