# Generated by Django 3.2.8 on 2021-11-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_botdetails_first_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField()),
                ('timestamp', models.TextField()),
                ('questions', models.TextField()),
                ('answers', models.TextField()),
            ],
            options={
                'db_table': 'chat_logs',
            },
        ),
    ]
