# Generated by Django 3.2.8 on 2021-11-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_chatlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlogs',
            name='botname',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatlogs',
            name='username',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
