# Generated by Django 3.2.8 on 2021-11-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211108_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('db_file_name', models.TextField()),
            ],
            options={
                'db_table': 'database_files',
            },
        ),
    ]
